# Generated by Django 5.1 on 2024-08-29 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Quantidade')),
                ('reason', models.CharField(max_length=255, verbose_name='motivo da movimentação')),
                ('product_id', models.CharField(default='', max_length=255, verbose_name='id do produto')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], default='IN', max_length=3)),
                ('date', models.DateField(blank=True, null=True, verbose_name='data da movimentação')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255, verbose_name='codigo do produto')),
                ('avaliable', models.BooleanField(default=True)),
                ('removed', models.BooleanField(default=False)),
                ('sotck_quantiy', models.PositiveIntegerField(default='0')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movements')),
            ],
        ),
    ]
