# Generated by Django 5.1 on 2024-08-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movements_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saida')], default='IN', max_length=10),
        ),
    ]
