# Generated by Django 5.1 on 2024-08-30 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='movement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.movements'),
        ),
    ]
