# Generated by Django 5.1 on 2024-08-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_movements_movement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movements',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='', max_length=255, verbose_name='id do produto'),
        ),
    ]
