# Generated by Django 5.1 on 2024-08-30 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_movements_product_id_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='movements',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.product', verbose_name='id do produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movements',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=10),
        ),
    ]
